### ISSUE TITLE
UX: range feedback

### ISSUE THREAD

**Issue by hadrienl** [Terralego/terra-front#93] opened 2019-09-09 08:29 UTC
Recent refacto on range component to have better performance breaks UX as you can see in this video :

![range-ux-bug](https://user-images.githubusercontent.com/225382/64515300-9ecf2080-d2ec-11e9-830a-fb4493fd2030.gif)

**Comment by SebCorbin** [comment] 2019-09-09 08:31
Duplicate of #80, see #87

**Closed by SebCorbin** 2019-09-09 08:31 UTC
Labels: bug
